spring:
  application:
    name: chat
  main:
    web-application-type: reactive
  web:
    resources:
      add-mappings: true
      static-locations: classpath:/static/
grpc:
  server:
    address: chat-model.chat.svc.cluster.local:50052